### ISSUE TITLE
concourse-alpine uaac not working

### ISSUE THREAD

**Issue by kkellner** [ECSTeam/docker-images#9]
when using uaac and trying to "target", we get the following error:

failed to access https://10.156.92.5:8443: Did not recognize your adapter specification (cannot load such file -- json/ext/parser).

I'm assuming there is a missing ruby gem or some other package in the alpine image.  Works fine with ubuntu image.

**Comment by naulta** [comment]
This needs the multi json lib. Olesya will investigate.

**Comment by OlesyaTishkina** [comment]
Just pushed the fixed and upgraded version.
